### PR TITLE
update to Go 1.16

### PR DESCRIPTION
**Pull request by billinghamj**
Gonna be honest, I have no idea how your build process works! I'm guessing this is far from what's required, but happy to add on further changes as needed.

This is needed to enable support for `arm64/darwin` - i.e. Apple Silicon/M1 Macs.

Relates to https://github.com/hashicorp/terraform/issues/27257

### CODE REVIEW

**Comment by billinghamj** [comment]
@eLobeto Is this something you can take a look at, or give any pointers on? :)

**Comment by eLobeto** [comment]
Hey! Sorry for the delay, didn't see the original email. Is there any particular reason you're using this fork? I made this a while back to get around a timeout issue we were seeing so I just bumped the timeout to 30 mins. If you need that, I'm happy to merge, otherwise you're probably better off using the official provider!

**Comment by billinghamj** [comment]
The official

**Comment by billinghamj** [comment]
The official provider has been fully deprecated and is no longer being released sadly. So this one is the only one still available on the registry! https://registry.terraform.io/search/providers?q=rancher

I have now published one of my own too: https://registry.terraform.io/providers/billinghamj/rancher/latest (with the arm64 binaries added) but could be beneficial for there to be just one defacto source

I switched mine to GitHub actions too, as that seems to be the recommended release setup at present

**Comment by billinghamj** [comment]
Closing due to inactivity - we'll just settle with my fork for now

**Pull request closed without merging**
